import Navbar from "@/components/Navbar";
import "./globals.css";
import { Comfortaa } from "next/font/google";
import Providers from "./providers";

const inter = Comfortaa({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="bg-white dark:bg-violet-950 min-h-screen transition-all duration-300">
            <Navbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
