"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import { Comfortaa } from "next/font/google";
import { useState } from "react";

const inter = Comfortaa({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <html className={darkMode && "dark"} lang="en">
      <body className={inter.className}>
        <div className="bg-white dark:bg-violet-950 min-h-screen transition-all duration-300">
          <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
          {children}
        </div>
      </body>
    </html>
  );
}
